python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202305/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202306/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202307/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202308/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202309/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202310/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202311/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202312/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202401/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202402/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202403/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202404/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202405/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202406/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202407/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202408/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202409/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202410/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202411/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202412/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202501/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202502/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202503/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202504/map/52000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/11000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/26000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/27000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/28000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/29000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/30000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/31000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/36000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/41000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/42000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/43000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/44000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/45000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/46000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/47000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/48000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/50000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/51000/TL_SCCO_GEMD
python -Xgil=0 cli/merge_geohash.py --base=/disk/nvme1t/geocoder-api-db/rocks_hd_history-debug --input=/disk/hdd-lv/juso-data/전체분/202505/map/52000/TL_SCCO_GEMD
