from enum import Enum


class AddressCls(Enum):
    NOT_ADDRESS = "NOT_ADDRESS"
    JIBUN_ADDRESS = "JIBUN_ADDRESS"
    BLD_ADDRESS = "BLD_ADDRESS"
    ROAD_ADDRESS = "ROAD_ADDRESS"

    ROAD_END_ADDRESS = "ROAD_END_ADDRESS"
    RI_END_ADDRESS = "RI_END_ADDRESS"
    H4_END_ADDRESS = "H4_END_ADDRESS"
    H23_END_ADDRESS = "H23_END_ADDRESS"
    H1_END_ADDRESS = "H1_END_ADDRESS"
    UNRECOGNIZABLE_ADDRESS = "UNRECOGNIZABLE_ADDRESS"
